project: minigrid_UED_Checkpoint
run_name: None
seed: 913472234
# === Train vs Eval ===
mode: train
checkpoint_directory: None
checkpoint_to_eval: -1
# === CHECKPOINTING ===
checkpoint_save_interval: -1
max_number_of_checkpoints: 60
# === EVAL ===
eval_freq: 100
eval_num_attempts: 10
eval_levels: [
    "SixteenRooms",
    "SixteenRooms2",
    "Labyrinth",
    "LabyrinthFlipped",
    "Labyrinth2",
    "StandardMaze",
    "StandardMaze2",
    "StandardMaze3",
]

# === ENV CONFIG ===
agent_view_size: 5

# === WandB ===
group: DEGen
log_animations: False